### PR TITLE
fix: CHISQ functions now handle booleans and deg_freedom has an upper bound

### LINKED ISSUE #734: CHISQ functions should handle boolean values
Similarly to #672, CHISQ functions should treat booleans as their respective numeric value. IronCalc instead treats them as just booleans, returning a #VALUE! error with a message "Expecting number".

## Test File
[CHISQ.xlsx](https://github.com/user-attachments/files/25026521/CHISQ.xlsx)

## Reproduction
The following examples show the failing cases:

| Cell | Formula | Excel | IronCalc | Notes | 
|---|---|---|---|---|
| D69 | `=CHISQ.DIST(TRUE, 7, TRUE)` | 0.99954704... | `#VALUE!` | Values as booleans |
| E69 | `=CHISQ.INV(D69, TRUE)` | 1 | `#VALUE!` | Values as booleans |
| C52 | `=CHISQ.DIST.RT(12.3, TRUE)` |  0.000452958... | `#VALUE!` | Values as booleans |
| D52 | `=CHISQ.DIST.RT(C52, TRUE)` |  12.2999999... | `#VALUE!` | Values as booleans |

### PR DESCRIPTION
**Pull request by elsaminsut**
This PR fixes #734 and #735. Now the set of CHISQ functions (CHISQ.DIST, CHISQ.INV, CHISQ.DIST.RT and CHISQ.INV.RT) can handle boolean values, following the behavior in Excel. It also adds an upper domain limit (10^10) for the _degrees of freedom_ argument. 

Some unit tests have been added as well to check the fix works as intended.

### CODE REVIEW

File: base/src/test/statistical/test_fn_chisq.rs [hunk 1]
```diff
@@ -121,8 +133,10 @@ fn test_fn_chisq_inv_rt_smoke() {
     // probability < 0 or > 1 -> #NUM!
     model._set("A5", "=CHISQ.INV.RT(-0.1, 4)");
     model._set("A6", "=CHISQ.INV.RT(1.1, 4)");
-    // deg_freedom < 1 -> #NUM!
+    // deg_freedom < 1 or > 10^10 -> #NUM!
     model._set("A7", "=CHISQ.INV.RT(0.5, 0)");
+    model._set("A8", "=CHISQ.INV.RT(1, 10000000000)");
```
Comment (nhatcher) [inline base/src/test/statistical/test_fn_chisq.rs:138]: You should use the group separator also in tests

File: base/src/test/statistical/test_fn_chisq.rs [hunk 2]
```diff
@@ -54,8 +58,10 @@ fn test_fn_chisq_dist_rt_smoke() {
     // Domain errors
     // x < 0 -> #NUM!
     model._set("A5", "=CHISQ.DIST.RT(-1, 4)");
-    // deg_freedom < 1 -> #NUM!
+    // deg_freedom < 1 or > 10^10 -> #NUM!
     model._set("A6", "=CHISQ.DIST.RT(0.5, 0)");
+    model._set("A7", "=CHISQ.DIST.RT(0, 10000000000)");
+    model._set("A8", "=CHISQ.DIST.RT(0, 10000000001)");
```
Comment (nhatcher) [inline base/src/test/statistical/test_fn_chisq.rs:64]: This can be `MAX_FREEDOM_NUMBER+1`

Comment (nhatcher) [reply base/src/test/statistical/test_fn_chisq.rs:64]: Also I think this needs to be tested in Excel. Is there any reason why we do this? (just curious)

Comment (elsaminsut) [reply base/src/test/statistical/test_fn_chisq.rs:64]: The xlsx test failed, that's how I found the bug. In the documentation, this upper bound is explicitly mentioned and I wanted to test whether IronCalc had it or not (turns out it didn't!).

Will fix readability in the tests in my next PR.
